name: Build and Deploy

on:
  push:
    branches:
      - main  # 코드를 푸시할 때마다 실행합니다.

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu 환경에서 실행합니다.

    steps:
      - name: Checkout Repository  # 리포지토리 체크아웃
        uses: actions/checkout@v2
      
      - name: Install Dependencies  # 종속성 설치
        run: npm install  # npm을 사용하여 종속성을 설치합니다.
      
      - name: Build Project  # 프로젝트 빌드
        run: npm run build  # npm을 사용하여 프로젝트를 빌드합니다.

      - name: Deploy to GitHub Pages  # GitHub Pages로 배포
        uses: JamesIves/github-pages-deploy-action@3.7.1  # GitHub Pages 배포 액션을 사용합니다.
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # GitHub Personal Access Token을 사용하여 배포합니다.
          BRANCH: gh-pages  # 배포할 브랜치를 지정합니다.
          FOLDER: build  # 배포할 폴더를 지정합니다. 여기서는 빌드된 파일이 있는 폴더를 지정합니다.
