name: Build and Deploy Website

on:
  push:
    branches:
      - main  # 웹사이트의 소스 코드가 변경될 때마다 실행

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 코드 저장소를 체크아웃하여 작업 환경으로 가져옴
    
    - name: Convert Markdown to HTML
      uses: jasonetco/marked-action@v2
      with:
        args: --input ./docs --output ./public  # Markdown 파일을 HTML로 변환하여 public 디렉터리에 저장
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub 토큰 사용하여 인증
        publish_dir: ./public  # 빌드된 웹사이트 파일이 있는 디렉터리
        force_orphan: true  # 기존 브랜치를 무시하고 새로운 브랜치에 커밋
